RabbitMQDemo/Models/AnswerModel.cs
namespace RabbitMQDemo.Models
{
    public record AnswerModel(ulong Id, string Text);
}

RabbitMQDemo/Models/EmailModel.cs
using ProtoBuf;

namespace RabbitMQDemo.Models
{
    [ProtoContract]
    public class EmailModel
    {
        [ProtoMember(1)]
        public string? Email { get; set; }
        [ProtoMember(2)]
        public string? Subject { get; set; }
        [ProtoMember(3)]
        public string? Body { get; set; }
    }
}

RabbitMQDemo/Models/QuestionModel.cs
namespace RabbitMQDemo.Models
{
    public record QuestionModel(string Email, string Text, ulong Id);
}

RabbitMQDemo/Models/SendEmailModel.cs
namespace RabbitMQDemo.Models
{
    public class SendEmailModel
    {
        public string? Emails { get; set; }
        public string? Subject { get; set; }
        public string? Body { get; set; }
    }
}

RabbitMQDemo/Controllers/HomeController.cs
using ExternalLogic;
using ExternalLogic.Models;
using Microsoft.AspNetCore.Mvc;

namespace RabbitMQDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly IEmailingService _emailingService;
        private readonly ISupportService _supportService;

        public HomeController(IEmailingService emailingService, ISupportService supportService)
        {
            _emailingService = emailingService;
            _supportService = supportService;
        }

        public JsonResult GetMessagingProgress(string id)
        {
            ProgressModel? res = _emailingService.GetProgress(id);

            return new JsonResult(new
            {
                total = res.Total,
                processed = res.Processed + res.Failed,
                errors = res.Failed
            });
        }

        public JsonResult IsConnectionAlive()
        {
            bool res = false;

            string? key = Request.Cookies["support-session"];
            if (!string.IsNullOrEmpty(key))
            {
                res = _supportService.IsConnectionAlive(key);
            }

            return new JsonResult(new
            {
                result = res
            });
        }

        public ActionResult SendNack(ulong id)
        {
            string? key = Request.Cookies["support-session"];
            if (string.IsNullOrEmpty(key)) return BadRequest();

            _supportService.DiscardMessage(key, id);

            return Ok();
        }
    }
}

RabbitMQDemo/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RabbitMQDemo.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RabbitMQDemo/Pages/Emailing.cshtml.cs
using ExternalLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitMQDemo.Models;

namespace RabbitMQDemo.Pages
{
    public class EmailingModel : PageModel
    {
        private readonly IEmailingService _emailingService;

        public EmailingModel(IEmailingService emailingService)
        {
            _emailingService = emailingService;
        }

        public void OnGet()
        {
        }

        [BindProperty]
        public SendEmailModel? EmailsModel { get; set; }

        public IActionResult OnPostNewEmail()
        {
            string[]? emails = EmailsModel?.Emails?.Split(',');

            if (emails == null || emails.Length == 0 || string.IsNullOrEmpty(EmailsModel?.Subject) || string.IsNullOrEmpty(EmailsModel?.Body))
            {
                return RedirectToPage("./Emailing");
            }

            string id = _emailingService.EnqueueEmailing(emails, EmailsModel.Subject, EmailsModel.Body);

            return RedirectToPage("./MessagingProgress", new { id });
        }
    }
}

RabbitMQDemo/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RabbitMQDemo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RabbitMQDemo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RabbitMQDemo.Pages
{
    public class IndexModel : PageModel
    {
        //private readonly ILogger<IndexModel> _logger;

        public IndexModel() { }

        public void OnGet()
        {

        }
    }
}

RabbitMQDemo/Pages/MessagingProgress.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RabbitMQDemo.Pages
{
    public class MessagingProgressModel : PageModel
    {
        public string? Id { get; set; }
        
        public void OnGet(string id = "0")
        {
            Id = id;
        }
    }
}

RabbitMQDemo/Pages/Support.cshtml.cs
using ExternalLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RabbitMQDemo.Pages
{
    public class SupportModel : PageModel
    {
        private readonly ISupportService _support;
        public SupportModel(ISupportService support)
        {
            _support = support;
        }

        public void OnGet()
        {
        }

        [BindProperty]
        public Models.QuestionModel? Question { get; set;}

        public ActionResult OnPost()
        {
            if(Question == null || string.IsNullOrEmpty(Question.Email) || string.IsNullOrEmpty(Question.Text)) return RedirectToPage("Support");

            _support.AskQuestion(Question.Email, Question.Text);

            return RedirectToPage("Support");
        }
    }
}

RabbitMQDemo/Pages/SupportAnswer.cshtml.cs
using ExternalLogic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RabbitMQDemo.Models;

namespace RabbitMQDemo.Pages
{
    public class SupportAnswerModel : PageModel
    {
        private readonly ISupportService _support;
        public SupportAnswerModel(ISupportService support)
        {
            _support = support;
        }

        public string? Message { get; set; }
        public Models.QuestionModel? Question { get; set; }

        public void OnGet()
        {
            string key;
            if (Request.Cookies.ContainsKey("support-session") && !string.IsNullOrEmpty(Request.Cookies["support-session"]))
            {
                key = Request.Cookies["support-session"]!;

                _support.Connect(key);
            }
            else
            {
                key = _support.Connect();
                Response.Cookies.Append("support-session", key, new CookieOptions { HttpOnly = true, IsEssential = true });
            }

            ExternalLogic.Models.QuestionModel? question = _support.GetNextQuestion(key, out ulong deliveryTag);

            if (question == null)
            {
                Message = "There is no new questions! Great job!";
                return;
            }

            Question = new Models.QuestionModel(question.Email, question.Text, deliveryTag);
        }

        [BindProperty]
        public AnswerModel? Answer { get; set; }

        public IActionResult OnPost()
        {
            if(Answer == null || string.IsNullOrEmpty(Answer.Text) || Answer.Id == 0) return RedirectToPage("SupportAnswer");
            string? key = Request.Cookies["support-session"];
            if(string.IsNullOrEmpty(key)) return RedirectToPage("SupportAnswer");
            
            //Send email with answer..

            _support.MarkAsAnswered(key, Answer.Id);

            return RedirectToPage("SupportAnswer");
        }
    }
}

RabbitMQDemo/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}

<section>
    <p>This is demo project for practicing with rabbitmq queues.</p>
    <p>There is two queues:</p>
    <ol>
        <li>Mailing queue - for sending series of emails, with progress tracking and error handling.</li>
        <li>Support queue - for support calls, persistent, without db involvement.</li>
    </ol>
    <p>Powered by docker.</p>
</section>

RabbitMQDemo/Pages/Emailing.cshtml
@page
@model EmailingModel
@{
    ViewData["Title"] = "Emailing";
}

<div class="text-center">
    <h1 class="display-4">@ViewData["Title"]</h1>
    <p>
        Emails are comma-separated.<br />
        Email messaging service will split emails into separate email messages, put them into RabbitMQ queue and process (send).<br/>
        After sending form you will see progress of emails sending.
    </p>
</div>
<section>
    <form asp-page-handler="NewEmail" method="post">
        <div class="mb-3">
            <input class="form-control" name="emails" placeholder="Email" />
        </div>
        <div class="mb-3">
            <input class="form-control" name="subject" placeholder="Subject"/>
        </div>
        <div class="mb-3">
            <textarea class="form-control" name="body" placeholder="Body"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Send</button>
        <button id="fill-form-btn" type="button" class="btn btn-secondary">Fill</button>
    </form>
</section>

<script>
    const btn = document.getElementById('fill-form-btn');
    btn.addEventListener('click', fillForm);

    function fillForm(e){
        const form = this.closest('form');
        form.querySelector('[name=emails]').value = 'email1@email.com, email2@email.com, email3@email.com, email4@email.com, email5@email.com, email6@email.com';
        form.querySelector('[name=subject]').value = 'Email subject';
        form.querySelector('[name=body]').value = 'Email body';
    }
</script>

RabbitMQDemo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>
        This is RabbitMQ demo project.<br/>
        There are two services:
        <ul>
            <li><b>Emailing service.</b> Used for sending email in batches. Emails puts into a queue and then send by external worker (hosted service for example).</li>
            <li><b>Support service.</b> Used for storing questions. Taking question from a queue and answering (persistance example).</li>
        </ul>
        Go to services through navbar at top.
    </p>
</div>

RabbitMQDemo/Pages/MessagingProgress.cshtml
@page
@model MessagingProgressModel
@{
    ViewData["Title"] = "Messaging progress";
}

<div class="text-center">
    <h1>@ViewData["Title"]</h1>
    <p><span id="info-label">Sending..</span> <span id="processed-count"></span>/<span id="total-count"></span></p>
    <p id="error-count-wrap" style="display: none;">Some messages not sended: <span id="error-count"></span></p>
    <div class="progress">
        <div id="progress" class="progress-bar" style="width: 0%;"><span id="progress-label"></span></div>
    </div>
    <div class="mt-3">
        <a asp-page="./Index" class="btn btn-primary">&lt; Back</a>
    </div>
</div>

<script>
    const id = '@Model.Id';
    const errorWrap = document.getElementById('error-count-wrap');
    const errorCount = document.getElementById('error-count');
    const totalCount = document.getElementById('total-count');
    const processedCount = document.getElementById('processed-count');
    const progress = document.getElementById('progress');
    const progressLabel = document.getElementById('progress-label');

    const polling = setInterval(() => {
        fetch('/home/getMessagingProgress?id='+id)
            .then(res => res.json())
            .then(data => {
                if(data.errors > 0){
                    errorWrap.style.display = 'block';
                    errorCount.innerText = data.errors;
                    progress.classList.add('bg-warning');
                } else {
                    errorWrap.style.display = 'none';
                }

                totalCount.innerText = data.total;
                processedCount.innerText = data.processed;

                const percent = (data.processed / data.total * 100).toFixed(0);
                progress.style.width = percent + '%';
                progressLabel.innerText = percent + '%';

                if(data.processed === data.total){
                    clearInterval(polling);
                    
                    progress.classList.remove('bg-warning');
                    if(data.errors === 0){
                        progress.classList.add('bg-success');
                    }else if (data.errors === data.total){
                        progress.classList.add('bg-danger');
                    }else{
                        progress.classList.add('bg-warning');
                    }

                    document.getElementById('info-label').innerText = 'Completed!';
                }
            });
    }, 1000);
</script>

RabbitMQDemo/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RabbitMQDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RabbitMQDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RabbitMQDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Emailing">Emailing</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" href="#" id="nav-dd-support" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Support
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="nav-dd-support" data-bs-popper="none">
                                <li><a class="dropdown-item" asp-area="" asp-page="/Support">Ask for support</a></li>
                                <li><a class="dropdown-item" asp-area="" asp-page="/SupportAnswer">Answer on support</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - RabbitMQDemo
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RabbitMQDemo/Pages/Support.cshtml
@page
@model SupportModel
@{
    ViewData["Title"] = "Support - ask";
}

<div class="text-center">
    <h1 class="display-4">Ask for support</h1>
    <p>
        Fill and submit the form. Your question will put into durable RabbitMQ queue and will processed on <a asp-page="./SupportAnswer">Answer page</a><br />
        No database involved, all data stored with RabbitMQ
    </p>
</div>
<section>
    <form method="post">
        <div class="mb-3">
            <input class="form-control" type="email" name="email" placeholder="Your email" />
        </div>
        <div class="mb-3">
            <textarea class="form-control" name="text" placeholder="Place your question here"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Ask</button>
        <button id="fill-form-btn" type="button" class="btn btn-secondary">Fill</button>
    </form>
</section>

<script>
    const btn = document.getElementById('fill-form-btn');
    btn.addEventListener('click', fillForm);

    function fillForm(e){
        const form = this.closest('form');
        form.querySelector('[name=email]').value = 'email@email.com';
        form.querySelector('[name=text]').value = 'Some question text.';
    }
</script>

RabbitMQDemo/Pages/SupportAnswer.cshtml
@page
@model SupportAnswerModel
@{
    ViewData["Title"] = "Support - answer";
}

<div class="text-center">
    <h1 class="display-4">Answer for support questions</h1>
    <p>
        If there are any messages in the queue you will take one and answer on it<br />
        If you not answer in session window (default: 5 minutes) your session will be abadonned and message returned to the queue
    </p>
    @if (!string.IsNullOrEmpty(Model.Message))
    {
        <h2>@Model.Message</h2>
    }
</div>
@if(Model.Question != null)
{
    <section id="answer-wrap">
        <p>from: @Model.Question.Email</p>
        <p>@Model.Question.Text</p>
        <form method="post">
            <input type="hidden" name="id" value="@Model.Question.Id" />
            <div class="mb-3">
                <textarea class="form-control" name="text" placeholder="Place your answer here"></textarea>
            </div>
            <button id="form-submit-btn" type="submit" class="btn btn-primary">Answer</button>
        </form>
    </section>
}

<script>
    sheduleSessionCheck();

    function isConnectionAlive(){
        fetch('/home/isConnectionAlive')
        .then(x=>x.json())
        .then(res => {
            if(!res.result){
                document.getElementById('form-submit-btn').disabled = true;

                const h2 = document.createElement('h2');
                h2.innerText = 'Your session is not alive anymore. Refresh page to get new question.';
                
                document.getElementById('answer-wrap').append(h2);

                sendNack();
            }else{
                sheduleSessionCheck();
            }
        })
    }

    function sheduleSessionCheck(){
        setTimeout(isConnectionAlive, 5000);
    }

    function sendNack(){
        const id = document.querySelector('#answer-wrap [name=id]').value;
        fetch('/home/sendNack/'+id);
    }
</script>